const REGION = "asia-southeast1";
const ROOT_PATH = "competitiveV2";
const PROTOCOL_VERSION = "competitive-v2-a2-1";
const SERVER_VERSION = "competitive-core-a2-1";
const CONFIG_VERSION = "competitive-test-config-1";
const SETTLEMENT_VERSION = "competitive-settlement-1";
const PLAYER_COUNT = 4;
const QUESTION_COUNT = 20;
const MAX_BODY_BYTES = 4_096;
const MAX_ID_LENGTH = 128;

const PHASE = Object.freeze({
  CREATED: "CREATED",
  WAITING_PLAYERS: "WAITING_PLAYERS",
  COUNTDOWN: "COUNTDOWN",
  QUESTION_OPEN: "QUESTION_OPEN",
  QUESTION_RESULT: "QUESTION_RESULT",
  NEXT_QUESTION: "NEXT_QUESTION",
  MATCH_FINISHED: "MATCH_FINISHED",
  SETTLEMENT_PENDING: "SETTLEMENT_PENDING",
  SETTLED: "SETTLED",
});

module.exports = {
  CONFIG_VERSION,
  MAX_BODY_BYTES,
  MAX_ID_LENGTH,
  PHASE,
  PLAYER_COUNT,
  PROTOCOL_VERSION,
  QUESTION_COUNT,
  REGION,
  ROOT_PATH,
  SERVER_VERSION,
  SETTLEMENT_VERSION,
};
